#!/usr/bin/env fish

stow common 

if uname -a | grep 'Darwin' > /dev/null
	# MacOS stuff
	stow dots-mac
	stow -d misc-mac -t ~/Library/Application\ Support/Code/User/ vscode
else
	# Linux stuff
	stow dots-linux
    stow -d other-files-linux -t ~/.config/Code/User/ vscode
end


