# addftinfo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/addftinfo.1
complete -c addftinfo -s v --description 'prints the version number.'

