# cksum
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/cksum.1
complete -c cksum -s o --description 'Use historic algorithms instead of the (superior) default one.'

