# colcrt
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/colcrt.1
complete -c colcrt -s 2 --description 'Cause all half-lines to be printed, effectively double spacing the output.'

