# comsat
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/comsat.8
complete -c comsat -s l --description 'The l option turns on syslogd 8 log messages.'

