# diskarbitrationd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/diskarbitrationd.8
complete -c diskarbitrationd -s d --description 'Report detailed information in /var/log/diskarbitrationd. log.'

