# echo
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/echo.1
complete -c echo -s n --description 'Do not print the trailing newline character.'

