# emacsclient
# Autogenerated from man page /usr/local/share/man/man1/emacsclient.1.gz
complete -c emacsclient -s c -l create-frame --description 'create a new frame instead of trying to use the current Emacs frame.'
complete -c emacsclient -s F -l frame-parameters --description 'set the parameters of a newly-created frame.'
complete -c emacsclient -o nw -s t -l tty --description 'open a new Emacs frame on the current terminal.'
complete -c emacsclient -s H --description 'print this usage information message and exit EXIT STATUS Normally, the exit …'

