# etags
# Autogenerated from man page /usr/local/share/man/man1/etags.1.gz
complete -c etags -l no-line-directive --description 'Ignore #line preprocessor directives in C and derived languages.'
complete -c etags -s Q -l class-qualify --description 'Qualify tag names with their class name in C++, ObjC, Java, and Perl.'

