# footprint
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/footprint.1
complete -c footprint -s a --description 'target all processes (will take much longer).'
complete -c footprint -s j --description 'also save a JSON representation of the data to the specified path.'
complete -c footprint -s f --description 'textual output should be formatted in bytes , Ar pages, or human-readable for…'
complete -c footprint -s p --description 'target the given process by name (can be used multiple times).'
complete -c footprint -s x --description 'exclude the given process by name or pid (can be used multiple times) Pp ofte…'
complete -c footprint -s t --description 'in addition to the supplied processes, target their children, grandchildren, …'
complete -c footprint -s s --description 'skip processes that are dirty tracked and have no outstanding XPC transaction…'
complete -c footprint -s v --description 'display vmmap-like output of address space layout.'
complete -c footprint -s y --description 'print only regions with dirty memory, and condense __TEXT, __DATA, and __LINK…'
complete -c footprint -s w --description 'show wide output with all columns (implies -swapped Fl -wired ).'
complete -c footprint -l swapped --description 'show swapped/compressed column, a subset of \'dirty\'.'
complete -c footprint -l wired --description 'show wired memory column, a subset of \'dirty\'.'
complete -c footprint -s h --description 'display help and exit El SAMPLE USAGE Pp footprint Mail WindowServer.'

