# git-gc
# Autogenerated from man page /usr/local/share/man/man1/git-gc.1
complete -c git-gc -l keep-largest-pack --description 'All packs except the largest pack and those marked with a .'
complete -c git-gc -l keep-base-pack --description 'gc. autoPackLimit to 0 disables automatic consolidation of packs.'

