# git-ls-remote
# Autogenerated from man page /usr/local/share/man/man1/git-ls-remote.1
complete -c git-ls-remote -l sort --description 'Sort based on the key given.'
complete -c git-ls-remote -s o -l server-option --description 'Transmit the given string to the server when communicating using protocol ver…'

