# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l worktree --description 'Similar to --local except that . git/config.'
complete -c git-config -l type --description 'git config will ensure that any input or output is valid under the given type…'
complete -c git-config -l no-type --description 'Un-sets the previously set type specifier (if one was previously set).'
complete -c git-config -l default --description 'When using --get, and the requested variable is not found, behave as if <valu…'
complete -c git-config -l '<type>' --description '.'
complete -c git-config -l no-replace-objects --description 'option was given on the command line.'
complete -c git-config -l rebase-merges --description 'option to git rebase so that the local merge commits are included in the reba…'
complete -c git-config -l column --description 'match.'
complete -c git-config -l color-moved-ws --description 'in git-diff(1).  difftool. <tool>. path.'
complete -c git-config -l negotiation-tip --description 'option for git-fetch(1).  format. attach.'
complete -c git-config -l keep-base-pack --description 'except that all packs that meet the threshold are kept, not just the base pac…'
complete -c git-config -l auto --description 'the commit-graph will be updated if housekeeping is required.'
complete -c git-config -l gpg-sign --description 'gpg. <format>. program.'
complete -c git-config -l no-curl --description 'option, the only supported method is CRAM-MD5.'
complete -c git-config -l delta-islands --description 'was passed.  Defaults to false.  repack. writeBitmaps.'

