# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
complete -c git-rebase -s r -l rebase-merges --description 'By default, a rebase will simply drop merge commits from the todo list, and p…'
complete -c git-rebase -l ancestry-path --description 'option will keep their original ancestry by default.'
complete -c git-rebase -s C --description 'Flags understood by both merge and interactive backends: oc o 2. 3.'

