# git-cat-file
# Autogenerated from man page /usr/local/share/man/man1/git-cat-file.1
complete -c git-cat-file -l unordered --description 'When --batch-all-objects is in use, visit objects in an order which may be mo…'

