# git-status
# Autogenerated from man page /usr/local/share/man/man1/git-status.1
complete -c git-status -l renames -l no-renames --description 'Turn on/off rename detection regardless of user configuration.'
complete -c git-status -l find-renames --description 'Turn on rename detection, optionally setting the similarity threshold.'

