# git-submodule
# Autogenerated from man page /usr/local/share/man/man1/git-submodule.1
complete -c git-submodule -l progress --description 'This option is only valid for add and update commands.'
complete -c git-submodule -l dissociate --description 'This option is only valid for add and update commands.'

