# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
complete -c git-merge -s F -l file --description 'Read the commit message to be used for the merge commit (in case one is creat…'

