# git-send-email
# Autogenerated from man page /usr/local/share/man/man1/git-send-email.1
complete -c git-send-email -l no-smtp-auth --description 'Disable SMTP authentication.  Short hand for --smtp-auth=none.'

