# git-mergetool
# Autogenerated from man page /usr/local/share/man/man1/git-mergetool.1
complete -c git-mergetool -s g -l gui --description 'When git-mergetool is invoked with the -g or --gui option the default merge t…'
complete -c git-mergetool -l no-gui --description 'This overrides a previous -g or --gui setting and reads the default merge too…'

