# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l interdiff --description 'As a reviewer aid, insert an interdiff into the cover letter, or as commentar…'
complete -c git-format-patch -l range-diff --description 'As a reviewer aid, insert a range-diff (see git-range-diff(1)) into the cover…'
complete -c git-format-patch -l creation-factor --description 'Used with --range-diff, tweak the heuristic which matches up commits between …'

