# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
complete -c git-fetch -l negotiation-tip --description 'By default, Git will report, to the server, commits reachable from all local …'
complete -c git-fetch -s o -l server-option --description 'Transmit the given string to the server when communicating using protocol ver…'

