# git-p4
# Autogenerated from man page /usr/local/share/man/man1/git-p4.1
complete -c git-p4 -l commit --description 'Submit only the specified commit or range of commits, instead of the full lis…'
complete -c git-p4 -l disable-rebase --description 'Disable the automatic rebase after all commits have been successfully submitt…'
complete -c git-p4 -l disable-p4sync --description 'Disable the automatic sync of p4/master from Perforce after commits have been…'

