# git-pack-objects
# Autogenerated from man page /usr/local/share/man/man1/git-pack-objects.1
complete -c git-pack-objects -l keep-pack --description 'This flag causes an object already in the given pack to be ignored, even if i…'
complete -c git-pack-objects -l keep-unreachable --description 'Objects unreachable from the refs in packs named with --unpacked= option are …'
complete -c git-pack-objects -l pack-loose-unreachable --description 'Pack unreachable loose objects (and their loose counterparts removed).'
complete -c git-pack-objects -l unpack-unreachable --description 'Keep unreachable objects in loose form.  This implies --revs.'
complete -c git-pack-objects -l delta-islands --description 'Restrict delta matches based on "islands".  See DELTA ISLANDS below.'

