# git-grep
# Autogenerated from man page /usr/local/share/man/man1/git-grep.1
complete -c git-grep -s r -l recursive --description 'Same as --max-depth=-1; this is the default.'
complete -c git-grep -l no-recursive --description 'Same as --max-depth=0.'
complete -c git-grep -l column --description 'Prefix the 1-indexed byte-offset of the first match from the start of the mat…'
complete -c git-grep -s o -l only-matching --description 'Print only the matched (non-empty) parts of a matching line, with each such p…'
complete -c git-grep -o '1;' --description '.'

