# git-reset
# Autogenerated from man page /usr/local/share/man/man1/git-reset.1
complete -c git-reset -l no-quiet --description 'Be quiet, only report errors.  The default behavior is set by the reset.'
complete -c git-reset -s C --description 'option instead.'
complete -c git-reset -l amend --description 'option to git-commit(1).'
complete -c git-reset -s c --description 'option specifies to pre-populate the commit message from the original message…'

