# git-replace
# Autogenerated from man page /usr/local/share/man/man1/git-replace.1
complete -c git-replace -l convert-graft-file --description 'Creates graft commits for all entries in $GIT_DIR/info/grafts and deletes tha…'

