# git-help
# Autogenerated from man page /usr/local/share/man/man1/git-help.1
complete -c git-help -l verbose --description 'When used with --all print description for all recognized commands.'
complete -c git-help -s c -l config --description 'List all available configuration variables.'

