# git-repack
# Autogenerated from man page /usr/local/share/man/man1/git-repack.1
complete -c git-repack -l keep-pack --description 'Exclude the given pack from repacking.  This is the equivalent of having .'
complete -c git-repack -s i -l delta-islands --description 'Pass the --delta-islands option to git-pack-objects, see git-pack-objects(1).'

