# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
complete -c git-pull -l negotiation-tip --description 'By default, Git will report, to the server, commits reachable from all local …'
complete -c git-pull -s o -l server-option --description 'Transmit the given string to the server when communicating using protocol ver…'

