# git-apply
# Autogenerated from man page /usr/local/share/man/man1/git-apply.1
complete -c git-apply -l intent-to-add --description 'When applying the patch only to the working tree, mark new files to be added …'
complete -c git-apply -o p2 --description 'a/dir/file will be applied directly to file.  The default is 1.'

