# git-interpret-trailers
# Autogenerated from man page /usr/local/share/man/man1/git-interpret-trailers.1
complete -c git-interpret-trailers -l no-divider --description 'Do not treat --- as the end of the commit message.'
complete -c git-interpret-trailers -l - --description 'as the end of the commit message.'

