# git-reflog
# Autogenerated from man page /usr/local/share/man/man1/git-reflog.1
complete -c git-reflog -l single-worktree --description 'By default when --all is specified, reflogs from all working trees are proces…'

