# git
# Autogenerated from man page /usr/local/share/man/man1/git.1
complete -c git -s P --description 'Do not pipe Git output into a pager.'
complete -c git -l list-cmds --description 'List commands by group.'

