# gsed
# Autogenerated from man page /usr/local/share/man/man1/gsed.1
complete -c gsed -l help --description 'display this help and exit.'
complete -c gsed -s n -l quiet -l silent --description 'suppress automatic printing of pattern space.'
complete -c gsed -l debug --description 'annotate program execution.'
complete -c gsed -s e -l expression --description 'add the script to the commands to be executed.'
complete -c gsed -s f -l file --description 'add the contents of script-file to the commands to be executed.'
complete -c gsed -l follow-symlinks --description 'follow symlinks when processing in place.'
complete -c gsed -s i -l in-place --description 'edit files in place (makes backup if SUFFIX supplied).'
complete -c gsed -s l -l line-length --description 'specify the desired line-wrap length for the `l\' command.'
complete -c gsed -l posix --description 'disable all GNU extensions.'
complete -c gsed -s E -s r -l regexp-extended --description 'use extended regular expressions in the script (for portability use POSIX -E).'
complete -c gsed -s s -l separate --description 'consider files as separate rather than as a single, continuous long stream.'
complete -c gsed -l sandbox --description 'operate in sandbox mode (disable e/r/w commands).'
complete -c gsed -s u -l unbuffered --description 'load minimal amounts of data from the input files and flush the output buffer…'
complete -c gsed -s z -l null-data --description 'separate lines by NUL characters.'
complete -c gsed -l version --description 'output version information and exit.'

