# gzexe
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/gzexe.1
complete -c gzexe -s d --description 'Decompress executables previously compressed by gzexe.'

