# httxt2dbm
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/httxt2dbm.8
complete -c httxt2dbm -s o --description 'Name of the output dbm files.  El EXAMPLES httxt2dbm i rewritemap.'

