# logresolve
# Autogenerated from man page /usr/local/share/man/man1/logresolve.1
complete -c logresolve -s c --description 'This causes logresolve to apply some DNS checks: after finding the hostname f…'

