# lpmove
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/lpmove.8.gz
complete -c lpmove -s E --description 'Forces encryption when connecting to the server.'
complete -c lpmove -s U --description 'Specifies an alternate username.'
complete -c lpmove -s h --description 'Specifies an alternate server.'

