# mount_9p
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/mount_9p.8
complete -c mount_9p -s r --description 'Mount filesystem as read-only.'
complete -c mount_9p -s h --description 'Print help message and exit.'

