# natpmpd
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/natpmpd.8
complete -c natpmpd -o x/y --description 'The private interfaces that need the use the service.  El NOTES com.'

