# nice
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/nice.1
complete -c nice -s n --description 'A positive or negative decimal integer used to modify the system scheduling p…'

