# postfix-tls
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/postfix-tls.1
complete -c postfix-tls -s T --description 'keyfile list uses the values of the corresponding Postfix server TLS key file…'

