# ppdhtml
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/ppdhtml.1.gz
complete -c ppdhtml -s D --description 'Sets the named variable for use in the source file.'
complete -c ppdhtml -s I --description 'Specifies an alternate include directory.'

