# ppdi
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/ppdi.1.gz
complete -c ppdi -s I --description 'Specifies an alternate include directory.'
complete -c ppdi -s o --description 'Specifies the PPD source file to update.'

