# ppdmerge
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/ppdmerge.1.gz
complete -c ppdmerge -s o --description 'Specifies the PPD file to create.'

