# snmpstatus
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/snmpstatus.1
complete -c snmpstatus -o Cf --description 'option is given, see below), but this variable will then be missing from the …'

