# suexec
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man8/suexec.8
complete -c suexec -s V --description 'If you are root, this option displays the compile options of suexec.'

