# uuidgen
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/share/man/man1/uuidgen.1
complete -c uuidgen -o hdr --description 'Emit CoreFoundation CFUUID-based source code for using the uuid in a header.'

