#! /bin/sh

#pkill sxhkd > /dev/null 2>&1
#sxhkd &

bspc monitor -d term emacs chrome 4 5 6 7 8 9 spotify

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
